name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-x64]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish ${{ matrix.rid }}
        run: dotnet publish SpellWithNato.csproj \
            -c Release \
            -f net9.0 \
            -r ${{ matrix.rid }} \
            --self-contained true \
            /p:PublishSingleFile=true

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/Release/net9.0/${{ matrix.rid }}/publish/SpellWithNato${{ matrix.rid == 'win-x64' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
