name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-x64]
    name: Build and Release ${{ matrix.rid }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish self-contained single file
        run: |
          dotnet publish SpellWithNato/SpellWithNato.csproj \
            -c Release \
            -f net9.0 \
            -r ${{ matrix.rid }} \
            --self-contained true \
            /p:PublishSingleFile=true

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          ext=""
          if [[ "${{ matrix.rid }}" == "win-x64" ]]; then ext=".exe"; fi
          cp "SpellWithNato/bin/Release/net9.0/${{ matrix.rid }}/publish/SpellWithNato$ext" \
             "artifacts/SpellWithNato-${{ matrix.rid }}$ext"

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
